- README.md
Our Team's project idea details added to ReadMe
> ReadMe updated with project title and description

- .eslintrc.json
- .travis.yml
- config/config.json
- models/index.js
- package-lock.json
- package.json
- server.js
Added starter files for the project
> Intial setup for project

- README.md
User story added to the ReadMe
> Added User story to the project

- public/index.html
> create index page

- config/config.json
- models/complaint.js
- models/user.js
- package-lock.json
- package.json
- server.js
Added user and complaint models
> created user and complaint models

- public/complaint.html
- public/register.html
- routes/HTMLRoutes.js
- server.js
Just some basic HTML Routes
close #14
> Add HTML Routes

- config/config.json
- models/report.js
- models/user.js
- public/login.html
- public/report.html
- routes/HTMLRoutes.js
changed modelname and fixed all related files
> changed model name

- assets/style/signon.css
- package-lock.json
- package.json
- public/login.html
- public/register.html
> Add register page

- routes/APIRoutes.js
- server.js
Here are the required API routes for the register and login page.
> Add APIRoutes

- assets/js/signon.js
- public/login.html
- public/register.html
- routes/APIRoutes.js
This PR adds sign-on support to both the registration page and the login page. 
close #22
> Implement user sign in and register logics

- config/config.json
- package-lock.json
- package.json
- server.js
Added Log requests to the console.(morgan)
> Added Morgan npm package

- config/config.json
- models/report.js
- models/user.js
added username and cityname in models
>  added username in usermode and cityname in reportmodel

- models/user.js
- routes/APIRoutes.js
added the username in router.js
>  added the username in the router

- assets/js/home.js
- assets/style/global.css
- assets/style/home.css
- public/index.html
Here is the homepage. 
close #26
> Implement Homepage

- assets/js/report.js
- assets/js/signon.js
- config/config.json
- public/index.html
- public/login.html
- public/register.html
- public/report.html
- routes/APIRoutes.js
- routes/HTMLRoutes.js
- server.js
Changed some of the files and created Report.js
> Implemented Report page

- assets/js/report.js
- assets/js/signon.js
- assets/style/report.css
- config/config.json
- models/report.js
- public/report.html
- routes/APIRoutes.js
added related fuctions and model for message
> added message in models and added realted functionality

- assets/js/view.js
- public/report.html
- public/view.html
- routes/APIRoutes.js
- routes/HTMLRoutes.js
> Reportbranch

- assets/js/report.js
- assets/style/global.css
- assets/style/report.css
- views/layouts/main.handlebars
- views/report.handlebars
> Improvement to Report Page

- views/index.handlebars
> Added Content to the main page

- assets/style/report.css
- routes/HTMLRoutes.js
- views/partials/report-row.handlebars
- views/report.handlebars
This is using handlebars partial. This has no delete logic
> Add Report Row

- assets/js/report.js
- assets/js/signon.js
- routes/APIRoutes.js
- routes/HTMLRoutes.js
This pull requests only add comments and cleanup unused code, comments, etc.
> Add comment and general cleanup

- assets/js/report.js
- assets/style/global.css
- assets/style/home.css
- assets/style/report.css
- assets/style/signon.css
- models/report.js
- models/user.js
- routes/APIRoutes.js
- routes/HTMLRoutes.js
- schema.sql
- views/index.handlebars
- views/layouts/main.handlebars
- views/login.handlebars
- views/partials/navbar.handlebars
- views/partials/report-row.handlebars
- views/register.handlebars
- views/report.handlebars
- views/view.handlebars
> updated comments
